project:
  type: website
  output-dir: docs

website:
  title: "Brooke Grazda"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: 
      light: lux
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full



