project:
  type: website
  output-dir: docs

website:
  title: "Brooke Grazda"
  navbar:
    logo: images/new_logo_04_11.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posts.qmd
        text: Data Science Projects
  page-footer:
    background: light
    left: Copyright 2024, Brooke Grazda
    right: This website is built with Github
format:
  html:
    theme: styles.scss
    mainfont: Frank Ruhl Libre
    toc: true
    page-layout: full



